repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: 'https://github.com/myint/autoflake'
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - '--in-place'
          - '--recursive'
          - '--expand-star-imports'
          - '--remove-unused-variables'
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - '--profile'
          - black
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.991
    hooks:
      - id: mypy
  - repo: 'https://github.com/pre-commit/mirrors-pylint'
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args:
          - >-
            --disable=W0142,W0403,W0613,W0232,R0903,R0913,C0103,R0914,C0304,F0401,W0402,E1101,W0614,C0111,C0301
        name: pylint
        entry: pylint
        language: python
        types:
          - python
  - repo: 'https://github.com/psf/black'
    rev: 22.10.0
    hooks:
      - id: black
  - repo: 'https://github.com/asottile/blacken-docs'
    rev: v1.12.1
    hooks:
      - id: blacken-docs
